import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import Navbar from "@/Components/Navbar";
import Footer from "@/Components/Footer";
import GameProvider from "@/context/GameContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Game Zoze",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-black ">
        <GameProvider>
          <Navbar></Navbar>
          <main className="flex-1 w-full">
            {children}
          </main>
          <Footer></Footer>
          <ToastContainer />
        </GameProvider>
      </body>
    </html>
  );
}
